/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/resourcemanager/v2/folders.proto

package com.google.cloud.resourcemanager.v2;

public interface FolderOperationOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.resourcemanager.v2.FolderOperation)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The display name of the folder.
   * </pre>
   *
   * <code>string display_name = 1;</code>
   *
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   *
   *
   * <pre>
   * The display name of the folder.
   * </pre>
   *
   * <code>string display_name = 1;</code>
   *
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString getDisplayNameBytes();

  /**
   *
   *
   * <pre>
   * The type of this operation.
   * </pre>
   *
   * <code>.google.cloud.resourcemanager.v2.FolderOperation.OperationType operation_type = 2;</code>
   *
   * @return The enum numeric value on the wire for operationType.
   */
  int getOperationTypeValue();
  /**
   *
   *
   * <pre>
   * The type of this operation.
   * </pre>
   *
   * <code>.google.cloud.resourcemanager.v2.FolderOperation.OperationType operation_type = 2;</code>
   *
   * @return The operationType.
   */
  com.google.cloud.resourcemanager.v2.FolderOperation.OperationType getOperationType();

  /**
   *
   *
   * <pre>
   * The resource name of the folder's parent.
   * Only applicable when the operation_type is MOVE.
   * </pre>
   *
   * <code>string source_parent = 3;</code>
   *
   * @return The sourceParent.
   */
  java.lang.String getSourceParent();
  /**
   *
   *
   * <pre>
   * The resource name of the folder's parent.
   * Only applicable when the operation_type is MOVE.
   * </pre>
   *
   * <code>string source_parent = 3;</code>
   *
   * @return The bytes for sourceParent.
   */
  com.google.protobuf.ByteString getSourceParentBytes();

  /**
   *
   *
   * <pre>
   * The resource name of the folder or organization we are either creating
   * the folder under or moving the folder to.
   * </pre>
   *
   * <code>string destination_parent = 4;</code>
   *
   * @return The destinationParent.
   */
  java.lang.String getDestinationParent();
  /**
   *
   *
   * <pre>
   * The resource name of the folder or organization we are either creating
   * the folder under or moving the folder to.
   * </pre>
   *
   * <code>string destination_parent = 4;</code>
   *
   * @return The bytes for destinationParent.
   */
  com.google.protobuf.ByteString getDestinationParentBytes();
}
