/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/resourcemanager/v2/folders.proto

package com.google.cloud.resourcemanager.v2;

public final class FoldersProto {
  private FoldersProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_resourcemanager_v2_Folder_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_resourcemanager_v2_Folder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_resourcemanager_v2_ListFoldersRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_resourcemanager_v2_ListFoldersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_resourcemanager_v2_ListFoldersResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_resourcemanager_v2_ListFoldersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_resourcemanager_v2_SearchFoldersRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_resourcemanager_v2_SearchFoldersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_resourcemanager_v2_SearchFoldersResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_resourcemanager_v2_SearchFoldersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_resourcemanager_v2_GetFolderRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_resourcemanager_v2_GetFolderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_resourcemanager_v2_CreateFolderRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_resourcemanager_v2_CreateFolderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_resourcemanager_v2_MoveFolderRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_resourcemanager_v2_MoveFolderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_resourcemanager_v2_UpdateFolderRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_resourcemanager_v2_UpdateFolderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_resourcemanager_v2_DeleteFolderRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_resourcemanager_v2_DeleteFolderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_resourcemanager_v2_UndeleteFolderRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_resourcemanager_v2_UndeleteFolderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_resourcemanager_v2_FolderOperation_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_resourcemanager_v2_FolderOperation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n-google/cloud/resourcemanager/v2/folder"
          + "s.proto\022\037google.cloud.resourcemanager.v2"
          + "\032\034google/api/annotations.proto\032\027google/a"
          + "pi/client.proto\032\037google/api/field_behavi"
          + "or.proto\032\031google/api/resource.proto\032\036goo"
          + "gle/iam/v1/iam_policy.proto\032\032google/iam/"
          + "v1/policy.proto\032#google/longrunning/oper"
          + "ations.proto\032 google/protobuf/field_mask"
          + ".proto\032\037google/protobuf/timestamp.proto\""
          + "\240\003\n\006Folder\022\021\n\004name\030\001 \001(\tB\003\340A\003\022\023\n\006parent\030"
          + "\002 \001(\tB\003\340A\002\022\024\n\014display_name\030\003 \001(\t\022T\n\017life"
          + "cycle_state\030\004 \001(\01626.google.cloud.resourc"
          + "emanager.v2.Folder.LifecycleStateB\003\340A\003\0224"
          + "\n\013create_time\030\005 \001(\0132\032.google.protobuf.Ti"
          + "mestampB\003\340A\003\0224\n\013update_time\030\006 \001(\0132\032.goog"
          + "le.protobuf.TimestampB\003\340A\003\"S\n\016LifecycleS"
          + "tate\022\037\n\033LIFECYCLE_STATE_UNSPECIFIED\020\000\022\n\n"
          + "\006ACTIVE\020\001\022\024\n\020DELETE_REQUESTED\020\002:A\352A>\n*cl"
          + "oudresourcemanager.googleapis.com/Folder"
          + "\022\020folders/{folder}\"{\n\022ListFoldersRequest"
          + "\022\031\n\006parent\030\001 \001(\tB\t\340A\002\372A\003\022\001*\022\026\n\tpage_size"
          + "\030\002 \001(\005B\003\340A\001\022\027\n\npage_token\030\003 \001(\tB\003\340A\001\022\031\n\014"
          + "show_deleted\030\004 \001(\010B\003\340A\001\"h\n\023ListFoldersRe"
          + "sponse\0228\n\007folders\030\001 \003(\0132\'.google.cloud.r"
          + "esourcemanager.v2.Folder\022\027\n\017next_page_to"
          + "ken\030\002 \001(\t\"V\n\024SearchFoldersRequest\022\026\n\tpag"
          + "e_size\030\001 \001(\005B\003\340A\001\022\027\n\npage_token\030\002 \001(\tB\003\340"
          + "A\001\022\r\n\005query\030\003 \001(\t\"j\n\025SearchFoldersRespon"
          + "se\0228\n\007folders\030\001 \003(\0132\'.google.cloud.resou"
          + "rcemanager.v2.Folder\022\027\n\017next_page_token\030"
          + "\002 \001(\t\"T\n\020GetFolderRequest\022@\n\004name\030\001 \001(\tB"
          + "2\340A\002\372A,\n*cloudresourcemanager.googleapis"
          + ".com/Folder\"n\n\023CreateFolderRequest\022\031\n\006pa"
          + "rent\030\001 \001(\tB\t\340A\002\372A\003\022\001*\022<\n\006folder\030\002 \001(\0132\'."
          + "google.cloud.resourcemanager.v2.FolderB\003"
          + "\340A\002\"|\n\021MoveFolderRequest\022@\n\004name\030\001 \001(\tB2"
          + "\340A\002\372A,\n*cloudresourcemanager.googleapis."
          + "com/Folder\022%\n\022destination_parent\030\002 \001(\tB\t"
          + "\340A\002\372A\003\022\001*\"\211\001\n\023UpdateFolderRequest\022<\n\006fol"
          + "der\030\001 \001(\0132\'.google.cloud.resourcemanager"
          + ".v2.FolderB\003\340A\002\0224\n\013update_mask\030\002 \001(\0132\032.g"
          + "oogle.protobuf.FieldMaskB\003\340A\002\"q\n\023DeleteF"
          + "olderRequest\022@\n\004name\030\001 \001(\tB2\340A\002\372A,\n*clou"
          + "dresourcemanager.googleapis.com/Folder\022\030"
          + "\n\020recursive_delete\030\002 \001(\010\"Y\n\025UndeleteFold"
          + "erRequest\022@\n\004name\030\001 \001(\tB2\340A\002\372A,\n*cloudre"
          + "sourcemanager.googleapis.com/Folder\"\371\001\n\017"
          + "FolderOperation\022\024\n\014display_name\030\001 \001(\t\022V\n"
          + "\016operation_type\030\002 \001(\0162>.google.cloud.res"
          + "ourcemanager.v2.FolderOperation.Operatio"
          + "nType\022\025\n\rsource_parent\030\003 \001(\t\022\032\n\022destinat"
          + "ion_parent\030\004 \001(\t\"E\n\rOperationType\022\036\n\032OPE"
          + "RATION_TYPE_UNSPECIFIED\020\000\022\n\n\006CREATE\020\001\022\010\n"
          + "\004MOVE\020\0022\276\017\n\007Folders\022\243\001\n\013ListFolders\0223.go"
          + "ogle.cloud.resourcemanager.v2.ListFolder"
          + "sRequest\0324.google.cloud.resourcemanager."
          + "v2.ListFoldersResponse\")\202\323\344\223\002\r\022\013/v2/fold"
          + "ers\332A\023parent,show_deleted\022\245\001\n\rSearchFold"
          + "ers\0225.google.cloud.resourcemanager.v2.Se"
          + "archFoldersRequest\0326.google.cloud.resour"
          + "cemanager.v2.SearchFoldersResponse\"%\202\323\344\223"
          + "\002\027\"\022/v2/folders:search:\001*\332A\005query\022\214\001\n\tGe"
          + "tFolder\0221.google.cloud.resourcemanager.v"
          + "2.GetFolderRequest\032\'.google.cloud.resour"
          + "cemanager.v2.Folder\"#\202\323\344\223\002\026\022\024/v2/{name=f"
          + "olders/*}\332A\004name\022\254\001\n\014CreateFolder\0224.goog"
          + "le.cloud.resourcemanager.v2.CreateFolder"
          + "Request\032\035.google.longrunning.Operation\"G"
          + "\202\323\344\223\002\025\"\013/v2/folders:\006folder\332A\rparent,fol"
          + "der\312A\031\n\006Folder\022\017FolderOperation\022\257\001\n\014Upda"
          + "teFolder\0224.google.cloud.resourcemanager."
          + "v2.UpdateFolderRequest\032\'.google.cloud.re"
          + "sourcemanager.v2.Folder\"@\202\323\344\223\002%2\033/v2/{fo"
          + "lder.name=folders/*}:\006folder\332A\022folder,up"
          + "date_mask\022\273\001\n\nMoveFolder\0222.google.cloud."
          + "resourcemanager.v2.MoveFolderRequest\032\035.g"
          + "oogle.longrunning.Operation\"Z\202\323\344\223\002\036\"\031/v2"
          + "/{name=folders/*}:move:\001*\332A\027name,destina"
          + "tion_parent\312A\031\n\006Folder\022\017FolderOperation\022"
          + "\252\001\n\014DeleteFolder\0224.google.cloud.resource"
          + "manager.v2.DeleteFolderRequest\032\'.google."
          + "cloud.resourcemanager.v2.Folder\";\202\323\344\223\002\026*"
          + "\024/v2/{name=folders/*}\332A\004name\332A\025name,recu"
          + "rsive_delete\022\242\001\n\016UndeleteFolder\0226.google"
          + ".cloud.resourcemanager.v2.UndeleteFolder"
          + "Request\032\'.google.cloud.resourcemanager.v"
          + "2.Folder\"/\202\323\344\223\002\"\"\035/v2/{name=folders/*}:u"
          + "ndelete:\001*\332A\004name\022\206\001\n\014GetIamPolicy\022\".goo"
          + "gle.iam.v1.GetIamPolicyRequest\032\025.google."
          + "iam.v1.Policy\";\202\323\344\223\002*\"%/v2/{resource=fol"
          + "ders/*}:getIamPolicy:\001*\332A\010resource\022\215\001\n\014S"
          + "etIamPolicy\022\".google.iam.v1.SetIamPolicy"
          + "Request\032\025.google.iam.v1.Policy\"B\202\323\344\223\002*\"%"
          + "/v2/{resource=folders/*}:setIamPolicy:\001*"
          + "\332A\017resource,policy\022\270\001\n\022TestIamPermission"
          + "s\022(.google.iam.v1.TestIamPermissionsRequ"
          + "est\032).google.iam.v1.TestIamPermissionsRe"
          + "sponse\"M\202\323\344\223\0020\"+/v2/{resource=folders/*}"
          + ":testIamPermissions:\001*\332A\024resource,permis"
          + "sions\032\220\001\312A#cloudresourcemanager.googleap"
          + "is.com\322Aghttps://www.googleapis.com/auth"
          + "/cloud-platform,https://www.googleapis.c"
          + "om/auth/cloud-platform.read-onlyB\311\001\n#com"
          + ".google.cloud.resourcemanager.v2B\014Folder"
          + "sProtoP\001ZNgoogle.golang.org/genproto/goo"
          + "gleapis/cloud/resourcemanager/v2;resourc"
          + "emanager\252\002\037Google.Cloud.ResourceManager."
          + "V2\312\002\037Google\\Cloud\\ResourceManager\\V2b\006pr"
          + "oto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.AnnotationsProto.getDescriptor(),
              com.google.api.ClientProto.getDescriptor(),
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.iam.v1.IamPolicyProto.getDescriptor(),
              com.google.iam.v1.PolicyProto.getDescriptor(),
              com.google.longrunning.OperationsProto.getDescriptor(),
              com.google.protobuf.FieldMaskProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
            });
    internal_static_google_cloud_resourcemanager_v2_Folder_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_resourcemanager_v2_Folder_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_resourcemanager_v2_Folder_descriptor,
            new java.lang.String[] {
              "Name", "Parent", "DisplayName", "LifecycleState", "CreateTime", "UpdateTime",
            });
    internal_static_google_cloud_resourcemanager_v2_ListFoldersRequest_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_resourcemanager_v2_ListFoldersRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_resourcemanager_v2_ListFoldersRequest_descriptor,
            new java.lang.String[] {
              "Parent", "PageSize", "PageToken", "ShowDeleted",
            });
    internal_static_google_cloud_resourcemanager_v2_ListFoldersResponse_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_resourcemanager_v2_ListFoldersResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_resourcemanager_v2_ListFoldersResponse_descriptor,
            new java.lang.String[] {
              "Folders", "NextPageToken",
            });
    internal_static_google_cloud_resourcemanager_v2_SearchFoldersRequest_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_resourcemanager_v2_SearchFoldersRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_resourcemanager_v2_SearchFoldersRequest_descriptor,
            new java.lang.String[] {
              "PageSize", "PageToken", "Query",
            });
    internal_static_google_cloud_resourcemanager_v2_SearchFoldersResponse_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_resourcemanager_v2_SearchFoldersResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_resourcemanager_v2_SearchFoldersResponse_descriptor,
            new java.lang.String[] {
              "Folders", "NextPageToken",
            });
    internal_static_google_cloud_resourcemanager_v2_GetFolderRequest_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_resourcemanager_v2_GetFolderRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_resourcemanager_v2_GetFolderRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_resourcemanager_v2_CreateFolderRequest_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_resourcemanager_v2_CreateFolderRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_resourcemanager_v2_CreateFolderRequest_descriptor,
            new java.lang.String[] {
              "Parent", "Folder",
            });
    internal_static_google_cloud_resourcemanager_v2_MoveFolderRequest_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_resourcemanager_v2_MoveFolderRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_resourcemanager_v2_MoveFolderRequest_descriptor,
            new java.lang.String[] {
              "Name", "DestinationParent",
            });
    internal_static_google_cloud_resourcemanager_v2_UpdateFolderRequest_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_resourcemanager_v2_UpdateFolderRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_resourcemanager_v2_UpdateFolderRequest_descriptor,
            new java.lang.String[] {
              "Folder", "UpdateMask",
            });
    internal_static_google_cloud_resourcemanager_v2_DeleteFolderRequest_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_resourcemanager_v2_DeleteFolderRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_resourcemanager_v2_DeleteFolderRequest_descriptor,
            new java.lang.String[] {
              "Name", "RecursiveDelete",
            });
    internal_static_google_cloud_resourcemanager_v2_UndeleteFolderRequest_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_resourcemanager_v2_UndeleteFolderRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_resourcemanager_v2_UndeleteFolderRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_resourcemanager_v2_FolderOperation_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_resourcemanager_v2_FolderOperation_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_resourcemanager_v2_FolderOperation_descriptor,
            new java.lang.String[] {
              "DisplayName", "OperationType", "SourceParent", "DestinationParent",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceReference);
    registry.add(com.google.longrunning.OperationsProto.operationInfo);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.iam.v1.IamPolicyProto.getDescriptor();
    com.google.iam.v1.PolicyProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
