/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/resourcemanager/v2/folders.proto

package com.google.cloud.resourcemanager.v2;

/**
 *
 *
 * <pre>
 * Metadata describing a long running folder operation
 * </pre>
 *
 * Protobuf type {@code google.cloud.resourcemanager.v2.FolderOperation}
 */
public final class FolderOperation extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.cloud.resourcemanager.v2.FolderOperation)
    FolderOperationOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use FolderOperation.newBuilder() to construct.
  private FolderOperation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private FolderOperation() {
    displayName_ = "";
    operationType_ = 0;
    sourceParent_ = "";
    destinationParent_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new FolderOperation();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private FolderOperation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              java.lang.String s = input.readStringRequireUtf8();

              displayName_ = s;
              break;
            }
          case 16:
            {
              int rawValue = input.readEnum();

              operationType_ = rawValue;
              break;
            }
          case 26:
            {
              java.lang.String s = input.readStringRequireUtf8();

              sourceParent_ = s;
              break;
            }
          case 34:
            {
              java.lang.String s = input.readStringRequireUtf8();

              destinationParent_ = s;
              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.google.cloud.resourcemanager.v2.FoldersProto
        .internal_static_google_cloud_resourcemanager_v2_FolderOperation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.resourcemanager.v2.FoldersProto
        .internal_static_google_cloud_resourcemanager_v2_FolderOperation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.resourcemanager.v2.FolderOperation.class,
            com.google.cloud.resourcemanager.v2.FolderOperation.Builder.class);
  }

  /**
   *
   *
   * <pre>
   * The type of operation that failed.
   * </pre>
   *
   * Protobuf enum {@code google.cloud.resourcemanager.v2.FolderOperation.OperationType}
   */
  public enum OperationType implements com.google.protobuf.ProtocolMessageEnum {
    /**
     *
     *
     * <pre>
     * Operation type not specified.
     * </pre>
     *
     * <code>OPERATION_TYPE_UNSPECIFIED = 0;</code>
     */
    OPERATION_TYPE_UNSPECIFIED(0),
    /**
     *
     *
     * <pre>
     * A create folder operation.
     * </pre>
     *
     * <code>CREATE = 1;</code>
     */
    CREATE(1),
    /**
     *
     *
     * <pre>
     * A move folder operation.
     * </pre>
     *
     * <code>MOVE = 2;</code>
     */
    MOVE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     *
     *
     * <pre>
     * Operation type not specified.
     * </pre>
     *
     * <code>OPERATION_TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int OPERATION_TYPE_UNSPECIFIED_VALUE = 0;
    /**
     *
     *
     * <pre>
     * A create folder operation.
     * </pre>
     *
     * <code>CREATE = 1;</code>
     */
    public static final int CREATE_VALUE = 1;
    /**
     *
     *
     * <pre>
     * A move folder operation.
     * </pre>
     *
     * <code>MOVE = 2;</code>
     */
    public static final int MOVE_VALUE = 2;

    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OperationType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OperationType forNumber(int value) {
      switch (value) {
        case 0:
          return OPERATION_TYPE_UNSPECIFIED;
        case 1:
          return CREATE;
        case 2:
          return MOVE;
        default:
          return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OperationType> internalGetValueMap() {
      return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<OperationType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OperationType>() {
          public OperationType findValueByNumber(int number) {
            return OperationType.forNumber(number);
          }
        };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
      return getDescriptor();
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
      return com.google.cloud.resourcemanager.v2.FolderOperation.getDescriptor()
          .getEnumTypes()
          .get(0);
    }

    private static final OperationType[] VALUES = values();

    public static OperationType valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OperationType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:google.cloud.resourcemanager.v2.FolderOperation.OperationType)
  }

  public static final int DISPLAY_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object displayName_;
  /**
   *
   *
   * <pre>
   * The display name of the folder.
   * </pre>
   *
   * <code>string display_name = 1;</code>
   *
   * @return The displayName.
   */
  @java.lang.Override
  public java.lang.String getDisplayName() {
    java.lang.Object ref = displayName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayName_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * The display name of the folder.
   * </pre>
   *
   * <code>string display_name = 1;</code>
   *
   * @return The bytes for displayName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getDisplayNameBytes() {
    java.lang.Object ref = displayName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      displayName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPERATION_TYPE_FIELD_NUMBER = 2;
  private int operationType_;
  /**
   *
   *
   * <pre>
   * The type of this operation.
   * </pre>
   *
   * <code>.google.cloud.resourcemanager.v2.FolderOperation.OperationType operation_type = 2;</code>
   *
   * @return The enum numeric value on the wire for operationType.
   */
  @java.lang.Override
  public int getOperationTypeValue() {
    return operationType_;
  }
  /**
   *
   *
   * <pre>
   * The type of this operation.
   * </pre>
   *
   * <code>.google.cloud.resourcemanager.v2.FolderOperation.OperationType operation_type = 2;</code>
   *
   * @return The operationType.
   */
  @java.lang.Override
  public com.google.cloud.resourcemanager.v2.FolderOperation.OperationType getOperationType() {
    @SuppressWarnings("deprecation")
    com.google.cloud.resourcemanager.v2.FolderOperation.OperationType result =
        com.google.cloud.resourcemanager.v2.FolderOperation.OperationType.valueOf(operationType_);
    return result == null
        ? com.google.cloud.resourcemanager.v2.FolderOperation.OperationType.UNRECOGNIZED
        : result;
  }

  public static final int SOURCE_PARENT_FIELD_NUMBER = 3;
  private volatile java.lang.Object sourceParent_;
  /**
   *
   *
   * <pre>
   * The resource name of the folder's parent.
   * Only applicable when the operation_type is MOVE.
   * </pre>
   *
   * <code>string source_parent = 3;</code>
   *
   * @return The sourceParent.
   */
  @java.lang.Override
  public java.lang.String getSourceParent() {
    java.lang.Object ref = sourceParent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceParent_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * The resource name of the folder's parent.
   * Only applicable when the operation_type is MOVE.
   * </pre>
   *
   * <code>string source_parent = 3;</code>
   *
   * @return The bytes for sourceParent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSourceParentBytes() {
    java.lang.Object ref = sourceParent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      sourceParent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATION_PARENT_FIELD_NUMBER = 4;
  private volatile java.lang.Object destinationParent_;
  /**
   *
   *
   * <pre>
   * The resource name of the folder or organization we are either creating
   * the folder under or moving the folder to.
   * </pre>
   *
   * <code>string destination_parent = 4;</code>
   *
   * @return The destinationParent.
   */
  @java.lang.Override
  public java.lang.String getDestinationParent() {
    java.lang.Object ref = destinationParent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationParent_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * The resource name of the folder or organization we are either creating
   * the folder under or moving the folder to.
   * </pre>
   *
   * <code>string destination_parent = 4;</code>
   *
   * @return The bytes for destinationParent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getDestinationParentBytes() {
    java.lang.Object ref = destinationParent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      destinationParent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!getDisplayNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, displayName_);
    }
    if (operationType_
        != com.google.cloud.resourcemanager.v2.FolderOperation.OperationType
            .OPERATION_TYPE_UNSPECIFIED
            .getNumber()) {
      output.writeEnum(2, operationType_);
    }
    if (!getSourceParentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sourceParent_);
    }
    if (!getDestinationParentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, destinationParent_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDisplayNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, displayName_);
    }
    if (operationType_
        != com.google.cloud.resourcemanager.v2.FolderOperation.OperationType
            .OPERATION_TYPE_UNSPECIFIED
            .getNumber()) {
      size += com.google.protobuf.CodedOutputStream.computeEnumSize(2, operationType_);
    }
    if (!getSourceParentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sourceParent_);
    }
    if (!getDestinationParentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, destinationParent_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.google.cloud.resourcemanager.v2.FolderOperation)) {
      return super.equals(obj);
    }
    com.google.cloud.resourcemanager.v2.FolderOperation other =
        (com.google.cloud.resourcemanager.v2.FolderOperation) obj;

    if (!getDisplayName().equals(other.getDisplayName())) return false;
    if (operationType_ != other.operationType_) return false;
    if (!getSourceParent().equals(other.getSourceParent())) return false;
    if (!getDestinationParent().equals(other.getDestinationParent())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DISPLAY_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayName().hashCode();
    hash = (37 * hash) + OPERATION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + operationType_;
    hash = (37 * hash) + SOURCE_PARENT_FIELD_NUMBER;
    hash = (53 * hash) + getSourceParent().hashCode();
    hash = (37 * hash) + DESTINATION_PARENT_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationParent().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.resourcemanager.v2.FolderOperation parseFrom(
      java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.resourcemanager.v2.FolderOperation parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.resourcemanager.v2.FolderOperation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.resourcemanager.v2.FolderOperation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.resourcemanager.v2.FolderOperation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.resourcemanager.v2.FolderOperation parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.resourcemanager.v2.FolderOperation parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.cloud.resourcemanager.v2.FolderOperation parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.resourcemanager.v2.FolderOperation parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.cloud.resourcemanager.v2.FolderOperation parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.resourcemanager.v2.FolderOperation parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.cloud.resourcemanager.v2.FolderOperation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.google.cloud.resourcemanager.v2.FolderOperation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   *
   *
   * <pre>
   * Metadata describing a long running folder operation
   * </pre>
   *
   * Protobuf type {@code google.cloud.resourcemanager.v2.FolderOperation}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.cloud.resourcemanager.v2.FolderOperation)
      com.google.cloud.resourcemanager.v2.FolderOperationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.cloud.resourcemanager.v2.FoldersProto
          .internal_static_google_cloud_resourcemanager_v2_FolderOperation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.resourcemanager.v2.FoldersProto
          .internal_static_google_cloud_resourcemanager_v2_FolderOperation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.resourcemanager.v2.FolderOperation.class,
              com.google.cloud.resourcemanager.v2.FolderOperation.Builder.class);
    }

    // Construct using com.google.cloud.resourcemanager.v2.FolderOperation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      displayName_ = "";

      operationType_ = 0;

      sourceParent_ = "";

      destinationParent_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.google.cloud.resourcemanager.v2.FoldersProto
          .internal_static_google_cloud_resourcemanager_v2_FolderOperation_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.resourcemanager.v2.FolderOperation getDefaultInstanceForType() {
      return com.google.cloud.resourcemanager.v2.FolderOperation.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.resourcemanager.v2.FolderOperation build() {
      com.google.cloud.resourcemanager.v2.FolderOperation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.resourcemanager.v2.FolderOperation buildPartial() {
      com.google.cloud.resourcemanager.v2.FolderOperation result =
          new com.google.cloud.resourcemanager.v2.FolderOperation(this);
      result.displayName_ = displayName_;
      result.operationType_ = operationType_;
      result.sourceParent_ = sourceParent_;
      result.destinationParent_ = destinationParent_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.resourcemanager.v2.FolderOperation) {
        return mergeFrom((com.google.cloud.resourcemanager.v2.FolderOperation) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.resourcemanager.v2.FolderOperation other) {
      if (other == com.google.cloud.resourcemanager.v2.FolderOperation.getDefaultInstance())
        return this;
      if (!other.getDisplayName().isEmpty()) {
        displayName_ = other.displayName_;
        onChanged();
      }
      if (other.operationType_ != 0) {
        setOperationTypeValue(other.getOperationTypeValue());
      }
      if (!other.getSourceParent().isEmpty()) {
        sourceParent_ = other.sourceParent_;
        onChanged();
      }
      if (!other.getDestinationParent().isEmpty()) {
        destinationParent_ = other.destinationParent_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.cloud.resourcemanager.v2.FolderOperation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage =
            (com.google.cloud.resourcemanager.v2.FolderOperation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object displayName_ = "";
    /**
     *
     *
     * <pre>
     * The display name of the folder.
     * </pre>
     *
     * <code>string display_name = 1;</code>
     *
     * @return The displayName.
     */
    public java.lang.String getDisplayName() {
      java.lang.Object ref = displayName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * The display name of the folder.
     * </pre>
     *
     * <code>string display_name = 1;</code>
     *
     * @return The bytes for displayName.
     */
    public com.google.protobuf.ByteString getDisplayNameBytes() {
      java.lang.Object ref = displayName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        displayName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * The display name of the folder.
     * </pre>
     *
     * <code>string display_name = 1;</code>
     *
     * @param value The displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayName(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      displayName_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The display name of the folder.
     * </pre>
     *
     * <code>string display_name = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearDisplayName() {

      displayName_ = getDefaultInstance().getDisplayName();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The display name of the folder.
     * </pre>
     *
     * <code>string display_name = 1;</code>
     *
     * @param value The bytes for displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayNameBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      displayName_ = value;
      onChanged();
      return this;
    }

    private int operationType_ = 0;
    /**
     *
     *
     * <pre>
     * The type of this operation.
     * </pre>
     *
     * <code>.google.cloud.resourcemanager.v2.FolderOperation.OperationType operation_type = 2;
     * </code>
     *
     * @return The enum numeric value on the wire for operationType.
     */
    @java.lang.Override
    public int getOperationTypeValue() {
      return operationType_;
    }
    /**
     *
     *
     * <pre>
     * The type of this operation.
     * </pre>
     *
     * <code>.google.cloud.resourcemanager.v2.FolderOperation.OperationType operation_type = 2;
     * </code>
     *
     * @param value The enum numeric value on the wire for operationType to set.
     * @return This builder for chaining.
     */
    public Builder setOperationTypeValue(int value) {

      operationType_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The type of this operation.
     * </pre>
     *
     * <code>.google.cloud.resourcemanager.v2.FolderOperation.OperationType operation_type = 2;
     * </code>
     *
     * @return The operationType.
     */
    @java.lang.Override
    public com.google.cloud.resourcemanager.v2.FolderOperation.OperationType getOperationType() {
      @SuppressWarnings("deprecation")
      com.google.cloud.resourcemanager.v2.FolderOperation.OperationType result =
          com.google.cloud.resourcemanager.v2.FolderOperation.OperationType.valueOf(operationType_);
      return result == null
          ? com.google.cloud.resourcemanager.v2.FolderOperation.OperationType.UNRECOGNIZED
          : result;
    }
    /**
     *
     *
     * <pre>
     * The type of this operation.
     * </pre>
     *
     * <code>.google.cloud.resourcemanager.v2.FolderOperation.OperationType operation_type = 2;
     * </code>
     *
     * @param value The operationType to set.
     * @return This builder for chaining.
     */
    public Builder setOperationType(
        com.google.cloud.resourcemanager.v2.FolderOperation.OperationType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      operationType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The type of this operation.
     * </pre>
     *
     * <code>.google.cloud.resourcemanager.v2.FolderOperation.OperationType operation_type = 2;
     * </code>
     *
     * @return This builder for chaining.
     */
    public Builder clearOperationType() {

      operationType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object sourceParent_ = "";
    /**
     *
     *
     * <pre>
     * The resource name of the folder's parent.
     * Only applicable when the operation_type is MOVE.
     * </pre>
     *
     * <code>string source_parent = 3;</code>
     *
     * @return The sourceParent.
     */
    public java.lang.String getSourceParent() {
      java.lang.Object ref = sourceParent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceParent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * The resource name of the folder's parent.
     * Only applicable when the operation_type is MOVE.
     * </pre>
     *
     * <code>string source_parent = 3;</code>
     *
     * @return The bytes for sourceParent.
     */
    public com.google.protobuf.ByteString getSourceParentBytes() {
      java.lang.Object ref = sourceParent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        sourceParent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * The resource name of the folder's parent.
     * Only applicable when the operation_type is MOVE.
     * </pre>
     *
     * <code>string source_parent = 3;</code>
     *
     * @param value The sourceParent to set.
     * @return This builder for chaining.
     */
    public Builder setSourceParent(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      sourceParent_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The resource name of the folder's parent.
     * Only applicable when the operation_type is MOVE.
     * </pre>
     *
     * <code>string source_parent = 3;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearSourceParent() {

      sourceParent_ = getDefaultInstance().getSourceParent();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The resource name of the folder's parent.
     * Only applicable when the operation_type is MOVE.
     * </pre>
     *
     * <code>string source_parent = 3;</code>
     *
     * @param value The bytes for sourceParent to set.
     * @return This builder for chaining.
     */
    public Builder setSourceParentBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      sourceParent_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destinationParent_ = "";
    /**
     *
     *
     * <pre>
     * The resource name of the folder or organization we are either creating
     * the folder under or moving the folder to.
     * </pre>
     *
     * <code>string destination_parent = 4;</code>
     *
     * @return The destinationParent.
     */
    public java.lang.String getDestinationParent() {
      java.lang.Object ref = destinationParent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationParent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * The resource name of the folder or organization we are either creating
     * the folder under or moving the folder to.
     * </pre>
     *
     * <code>string destination_parent = 4;</code>
     *
     * @return The bytes for destinationParent.
     */
    public com.google.protobuf.ByteString getDestinationParentBytes() {
      java.lang.Object ref = destinationParent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        destinationParent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * The resource name of the folder or organization we are either creating
     * the folder under or moving the folder to.
     * </pre>
     *
     * <code>string destination_parent = 4;</code>
     *
     * @param value The destinationParent to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationParent(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      destinationParent_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The resource name of the folder or organization we are either creating
     * the folder under or moving the folder to.
     * </pre>
     *
     * <code>string destination_parent = 4;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearDestinationParent() {

      destinationParent_ = getDefaultInstance().getDestinationParent();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The resource name of the folder or organization we are either creating
     * the folder under or moving the folder to.
     * </pre>
     *
     * <code>string destination_parent = 4;</code>
     *
     * @param value The bytes for destinationParent to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationParentBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      destinationParent_ = value;
      onChanged();
      return this;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.cloud.resourcemanager.v2.FolderOperation)
  }

  // @@protoc_insertion_point(class_scope:google.cloud.resourcemanager.v2.FolderOperation)
  private static final com.google.cloud.resourcemanager.v2.FolderOperation DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.google.cloud.resourcemanager.v2.FolderOperation();
  }

  public static com.google.cloud.resourcemanager.v2.FolderOperation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FolderOperation> PARSER =
      new com.google.protobuf.AbstractParser<FolderOperation>() {
        @java.lang.Override
        public FolderOperation parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new FolderOperation(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<FolderOperation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FolderOperation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.resourcemanager.v2.FolderOperation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
