/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/resourcemanager/v2/folders.proto

package com.google.cloud.resourcemanager.v2;

public interface UpdateFolderRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.resourcemanager.v2.UpdateFolderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Required. The new definition of the Folder. It must include a
   * a `name` and `display_name` field. The other fields
   * will be ignored.
   * </pre>
   *
   * <code>
   * .google.cloud.resourcemanager.v2.Folder folder = 1 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   *
   * @return Whether the folder field is set.
   */
  boolean hasFolder();
  /**
   *
   *
   * <pre>
   * Required. The new definition of the Folder. It must include a
   * a `name` and `display_name` field. The other fields
   * will be ignored.
   * </pre>
   *
   * <code>
   * .google.cloud.resourcemanager.v2.Folder folder = 1 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   *
   * @return The folder.
   */
  com.google.cloud.resourcemanager.v2.Folder getFolder();
  /**
   *
   *
   * <pre>
   * Required. The new definition of the Folder. It must include a
   * a `name` and `display_name` field. The other fields
   * will be ignored.
   * </pre>
   *
   * <code>
   * .google.cloud.resourcemanager.v2.Folder folder = 1 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   */
  com.google.cloud.resourcemanager.v2.FolderOrBuilder getFolderOrBuilder();

  /**
   *
   *
   * <pre>
   * Required. Fields to be updated.
   * Only the `display_name` can be updated.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   *
   * @return Whether the updateMask field is set.
   */
  boolean hasUpdateMask();
  /**
   *
   *
   * <pre>
   * Required. Fields to be updated.
   * Only the `display_name` can be updated.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   *
   * @return The updateMask.
   */
  com.google.protobuf.FieldMask getUpdateMask();
  /**
   *
   *
   * <pre>
   * Required. Fields to be updated.
   * Only the `display_name` can be updated.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   */
  com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder();
}
